force-app/main/default/objects/Contact/fields/Blacklist_Counts__c.field-meta.xml
<CustomField>
    <fullName>Blacklist_Counts__c</fullName>
    <label>Blacklist Counts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Blacklisted__c.field-meta.xml
<CustomField>
    <fullName>Blacklisted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blacklisted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Notes_for_Blacklist__c.field-meta.xml
<CustomField>
    <fullName>Notes_for_Blacklist__c</fullName>
    <label>Notes for Blacklist</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/updateContactBlacklist.cls
public class updateContactBlacklist {
	public class FlowInput{
         
                      
        
        @AuraEnabled @InvocableVariable
                        public String Id;
        @AuraEnabled @InvocableVariable
                        public String notes;
        			@AuraEnabled @InvocableVariable
                        public Boolean blacklist;
        
                     	
            @AuraEnabled @InvocableVariable
                      public List<Contact> mr = new List<Contact>(); 
                    
                     
        
    }
   @InvocableMethod(callout=false label='Blacklist Checkbox On Contact')
  public static void createWithdrawalHistory(List<FlowInput> No) {
      Id test= No[0].Id;
     boolean cValue = NO[0].blacklist;
      String notes = NO[0].notes;
     
    updateCheckboxes(test, cValue, notes);
  }
    
    @future
    public static void updateCheckboxes(Id rcdId, boolean cValue, String notes){
        Contact newCon = [Select id, blacklisted__c,Notes_for_Blacklist__c, Blacklist_Counts__c from contact where id=:rcdId];
        newCon.Blacklisted__c = cValue;
        newCon.Blacklist_Counts__c = 1;
        newCon.Notes_for_Blacklist__c = notes;
        update newCon;
    }

}