force-app/main/default/objects/Contact/fields/Blacklisted__c.field-meta.xml
<CustomField>
    <fullName>Blacklisted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blacklisted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SubscriptionType__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionType__c</fullName>
    <label>Subscription Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free</fullName>
                <default>true</default>
                <label>Free</label>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/createCandidateController.cls
public without sharing class createCandidateController {
    
    @AuraEnabled
    public static string createCandidate(String firstName, String lastName, string emailValue){
        system.debug(firstName);
        system.debug(lastName);
        system.debug(emailValue);
        try{
            user ut = [Select id, email, contactId from user where Username=:emailValue];
            
            
            Id cId = ut.contactId;
            Contact ct = [Select id, blacklisted__c from contact where id=:cId];
            
            
                if(ct.blacklisted__c)
                {
                    return 'There was an issue in logging into your account. Please contact the ISS team for more information.';
                    
                }
                else{
                    return 'This email address is already registered for an account';
                }
                
            
            
        }catch(exception e){
            List <Account> ac =[SELECT Name, Id FROM Account where Name ='EDUrecruit' LIMIT 1];
            Contact candidateContact = new Contact();
            candidateContact.FirstName = firstName;
            candidateContact.LastName = lastName;
            candidateContact.Email = emailValue;
            candidateContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Candidate').getRecordTypeId();
            candidateContact.AccountId = ac[0].Id;
            candidateContact.SubscriptionType__c = 'Trial';
            Insert candidateContact;
            return 'Thank you for registering. Your account has been created successfully and an email has been sent to you to complete the registration process.';
        }
        
        
        
        // List<Contact> lst = [Select id from Contact where email =:emailValue ];
        
        
        
    }
    
    
}